### ISSUE TITLE
how to cusotmize the prettier setting

### ISSUE THREAD

**Issue by xavier-professor** [quavedev/eslint-config#5]
I want to add the following prettier setting to package.json with your package, but I don't know to to do it:

"prettier": {
        "semicolons": true,
        "singleQuote": true,
        "trailingComma": "all",
        "tabWidth": 4,
        "printWidth": 120,
        "arrowParens": "always"
    }

**Comment by filipenevola** [comment]
Hi, this package already defines some prettier rules, do you want to override them?
